
SRC_DIR = src
VER_FILE = $(SRC_DIR)/define.sh

DIST_NAME = \
  $(shell grep "_NAME=" $(VER_FILE) | awk -F\" '{print $$2}')
DIST_VERSION = \
  $(shell grep "_VERSION=" $(VER_FILE) | awk -F\" '{print $$2}')

EXE_TGT = $(SRC_DIR)/$(DIST_NAME)

EXE_SRC_CORE_LIST = \
  src/debug.sh \
  src/varargs.sh \
  src/util.sh \
  src/root.sh \
  src/version.sh \
  src/arg.sh \
  src/info.sh \
  src/var.sh \
  src/var_usage_exp.sh \
  src/usage.sh \
  src/console.sh \
  src/theme.sh \
  src/display.sh \
  src/roll.sh \
  src/log.sh \
  src/notif.sh \
  src/action.sh \
  src/appli.sh \
  src/engine.sh

EXE_SRC_EXTRA_LIST = \
  src/job.sh \
  src/state.sh \
  src/prop_file.sh \
  src/net_cfg.sh \
  src/notif_mail.sh \
  src/notif_sms_free.sh

EXE_SRC_MAIN_LIST = \
  src/main_tpl.sh \
  src/main_tpl_makefile \
  Makefile \
  src/main_tpl_makefile_eof \
  src/main.sh

SRC_LIST = \
  src/define.sh \
  src/util_map.sh \
  src/util_list.sh \
  src/module.sh \
  src/which.sh \
  $(EXE_SRC_CORE_LIST) \
  $(EXE_SRC_EXTRA_LIST) \
  $(EXE_SRC_MAIN_LIST)

EXTRA_DIST = \
  ChangeLog \
  TODO \
  test/test.sh \
  test/cfg.sh \
  test/init.sh \
  test/module.sh

EXTRA_CLEAN = \
  test/log \
  test/notif \
  test/test.prop
