
.PHONY: usage info all init exe_lib_tgt doc
.PHONY: dist-gz dist-bz dist-xz dist dist-clean
.PHONY: install clean centos-docker
.PHONY: asciidoctor-docker-image do-asciidoctor-docker-image doc-clean

OS = $(shell uname -o)
ifeq ($(OS),Cygwin)
OS_CYGWIN = T
endif

ifneq ($(MAKECMDGOALS),usage)
include Makefile.cfg
endif

CHANGELOG_ADOC_FILE = ChangeLog.adoc

ifeq ($(ADOC_LIST),)
ADOC_LIST = $(wildcard doc/*.adoc)
ifeq ($(wildcard doc/$(CHANGELOG_ADOC_FILE)),)
ifeq ($(wildcard $(CHANGELOG_ADOC_FILE)),$(CHANGELOG_ADOC_FILE))
ADOC_LIST += doc/$(CHANGELOG_ADOC_FILE)
endif
endif
endif
DOC_HTML_LIST = $(ADOC_LIST:.adoc=.html)

INSTALL_BIN_FILE_LIST += $(EXE_TGT)
INSTALL_LIB_FILE_LIST += $(LIB_TGT)

DIST_TAR_Z = J
DIST_TAR_EXT = .tar.xz

ifeq ($(MAKECMDGOALS),install)
ifeq ($(INSTALL_DIR),)
$(error Define INSTALL_DIR variable)
endif
INSTALL_BIN_DIR = $(INSTALL_DIR)/bin
INSTALL_LIB_DIR = $(INSTALL_DIR)/lib
endif

MAKEFILE_LIST = Makefile Makefile.cfg

SRC_LIST_ALL = $(SRC_GENERATED_LIST) $(SRC_LIST)

EXTRA_DIST_ALL = $(EXTRA_DIST) $(EXTRA_ADOC_INCLUDE)
DIST_FILE_LIST = $(MAKEFILE_LIST) $(SRC_LIST) $(ADOC_LIST) $(EXTRA_DIST_ALL)

ASCIIDOCTOR_DOCKER_IMG = $(USER)/asciidoctor

DIST_DEFINE_VAR_PREFIX = $(shell echo $(patsubst %.sh,%,$(DIST_NAME)) | \
	sed -e "s/[^a-zA-Z0-9]/_/g" | tr '[a-z]' '[A-Z]')

DIST_DEFINE_DATETIME = $(shell date '+%F %T')

DIST_DEFINE_SUBST_VAR_LIST = DIST_DEFINE_VAR_PREFIX DIST_NAME DIST_VERSION \
	DIST_DEFINE_DATETIME CHANGELOG_ADOC_FILE
DIST_DEFINE_SED_ARGS = $(foreach var,$(DIST_DEFINE_SUBST_VAR_LIST), \
	-e "s!@$(var)@!$($(var))!g")

INFO_VAR_LIST = EXE_TGT LIB_TGT SRC_LIST SRC_GENERATED_LIST ADOC_LIST \
	GEN_PNG_LIST DIST_NAME DIST_VERSION EXTRA_DIST EXTRA_CLEAN \
	EXTRA_ADOC_INCLUDE

usage:
	@echo "Create 'Makefile.cfg' file with :"
	@echo
	@echo "  EXE_TGT = [ executable target ] or"
	@echo "  LIB_TGT = [ library target ]"
	@echo "  SRC_LIST = [ source files ]"
	@echo "  SRC_GENERATED_LIST = [ generated source files ]"
	@echo "  ADOC_LIST = [ adoc files ]"
	@echo "  GEN_PNG_LIST = [ generated PNG files ]"
	@echo "  DIST_NAME = [ distribution name ]"
	@echo "  DIST_VERSION = [ distribution version ]"
	@echo "  EXTRA_DIST = [ extra distribution files ]"
	@echo "  EXTRA_CLEAN = [ extra clean files ]"
	@echo "  EXTRA_ADOC_INCLUDE = [ extra adoc include files ]"
	@echo
	@echo "Usage : make [usage|all|init|exe_lib_tgt|doc|"
	@echo "              dist|install|clean|centos-docker]"
	@echo
	@echo "  usage : display this usage (default)"
	@echo "  info : display infos (variable values)"
	@echo "  all : execute targets with *"
	@echo "  exe_lib_tgt (*) : create '$(EXE_TGT) $(LIB_TGT)'"
	@echo "  doc (*) : create documentation"
	@echo "  dist (= dist-xz) : create distribution with format xz"
	@echo "  dist-gz : create distribution with format gz"
	@echo "  dist-bz : create distribution with format bz2"
	@echo "  install : install exe/lib in INSTALL_DIR directory"
	@echo "  clean : clean created files/directories"
	@echo "  centos-docker : start centos container"

info:
	@$(foreach var,$(INFO_VAR_LIST),echo "$(var)=[$($(var))]";)

all: exe_lib_tgt doc

exe_lib_tgt: $(EXE_TGT) $(LIB_TGT)

src/define_.sh: $(MAKEFILE_LIST)
	TAG=DEFINE_; grep "^#$$TAG" Makefile | \
	sed -e "s/#$$TAG###//" $(DIST_DEFINE_SED_ARGS) > $@

#DEFINE_###### Generated by Makefile at @DIST_DEFINE_DATETIME@
#DEFINE_###################################################################################
#DEFINE_###################################################################################
#DEFINE_###
#DEFINE_###readonly @DIST_DEFINE_VAR_PREFIX@_DIST_NAME="@DIST_NAME@"
#DEFINE_###readonly @DIST_DEFINE_VAR_PREFIX@_DIST_VERSION="@DIST_VERSION@"
#DEFINE_###
#DEFINE_###################################################################################
#DEFINE_###################################################################################
#DEFINE_###
#DEFINE_###readonly @DIST_DEFINE_VAR_PREFIX@_DEFINE_VAR_PREFIX="@DIST_DEFINE_VAR_PREFIX@"
#DEFINE_###
#DEFINE_###readonly @DIST_DEFINE_VAR_PREFIX@_CHANGELOG_ADOC_FILE=@CHANGELOG_ADOC_FILE@

$(EXE_TGT) $(LIB_TGT): $(SRC_LIST_ALL) $(MAKEFILE_LIST)
	@echo "#!/bin/sh" > $@
	@for f in $(SRC_LIST_ALL); \
	do \
		echo "Cat: [$$f]->[$@]"; \
		if [ "$$f" = "Makefile" ]; \
		then \
			cat $$f | sed -e "s|\\\\|\\\\\\\\|g" \
				-e "s|\\$$|\\\\$$|g" >> $@; \
		elif [ "$$f" = "src/main_tpl_makefile_eof" ]; \
		then \
			cat $$f >> $@; \
		else \
			echo "### Dist=[$(DIST_NAME)] File=[$$f]" >> $@; \
			cat $$f >> $@; \
		fi \
	done
	@chmod a+x $@

doc: asciidoctor-docker-image $(DOC_HTML_LIST)

doc/$(CHANGELOG_ADOC_FILE): $(CHANGELOG_ADOC_FILE)
	cp -f $< $@

%.html: %.adoc $(EXTRA_ADOC_INCLUDE)
	[ -n "$(OS_CYGWIN)" ] && SRC_VOL=$$(cygpath -ma .) || SRC_VOL=$$PWD; \
	docker run --rm -v "$$SRC_VOL":/documents $(ASCIIDOCTOR_DOCKER_IMG) \
	asciidoctor -r asciidoctor-diagram -o $@ \
	-a revnumber=$(DIST_VERSION) $<

dist-gz:
	make dist DIST_TAR_Z="z" DIST_TAR_EXT=".tar.gz"

dist-bz:
	make dist DIST_TAR_Z="j" DIST_TAR_EXT=".tar.bz2"

dist-xz:
	make dist

dist:
	@make dist-clean; \
	DIST=$(DIST_NAME)-$(DIST_VERSION); \
	mkdir $$DIST; \
	for f in $(DIST_FILE_LIST); \
	do \
		SRC=$$f; \
		DST=$$DIST/$$f; \
		mkdir -p $$(dirname $$DST); \
		cp $$SRC $$DST; \
	done; \
	tar cv$(DIST_TAR_Z)f $$DIST$(DIST_TAR_EXT) $$DIST; \
	rm -rf $$DIST

dist-clean:
	rm -rf $(DIST_NAME)-$(DIST_VERSION)*

install: all
	@rm -rf $(INSTALL_DIR)
	@if [ -n "$(INSTALL_BIN_FILE_LIST)" ]; \
	then \
		INSTALL_FILE_LIST=$(INSTALL_BIN_FILE_LIST); \
		INSTALL_DST_DIR=$(INSTALL_BIN_DIR); \
	elif [ -n "$(INSTALL_LIB_FILE_LIST)" ]; \
	then \
		INSTALL_FILE_LIST=$(INSTALL_LIB_FILE_LIST); \
		INSTALL_DST_DIR=$(INSTALL_LIB_DIR); \
	fi; \
	mkdir -p $$INSTALL_DST_DIR; \
	for f in $$INSTALL_FILE_LIST; \
	do \
		echo "Copy: [$$f]->[$$INSTALL_DST_DIR]"; \
		cp $$f $$INSTALL_DST_DIR; \
		chmod a+x $$INSTALL_DST_DIR/$$(basename $$f); \
	done

clean:
	rm -rf $(SRC_GENERATED_LIST) $(EXE_TGT) $(LIB_TGT) $(EXTRA_CLEAN)
	rm -rf tmp
	make dist-clean doc-clean

centos-docker: all
	[ -n "$(OS_CYGWIN)" ] && SRC_VOL=$$(cygpath -ma .) || SRC_VOL=$$PWD; \
	docker run -it -v "$$SRC_VOL":/home/soaf centos

asciidoctor-docker-image:
	@[ -z "$$(docker image ls -q $(ASCIIDOCTOR_DOCKER_IMG))" ] && \
	make do-asciidoctor-docker-image || true

do-asciidoctor-docker-image: Makefile
	TAG=DOCKERFILE; grep "^#$$TAG" Makefile | sed -e "s/^#$$TAG###//" | \
	docker build -t $(ASCIIDOCTOR_DOCKER_IMG) -

doc-clean:
	rm -f $(DOC_HTML_LIST) $(GEN_PNG_LIST) doc/$(CHANGELOG_ADOC_FILE)
	rm -rf doc/.asciidoctor

#DOCKERFILE###FROM centos
#DOCKERFILE###
#DOCKERFILE###RUN yum install -y ruby java python2 graphviz
#DOCKERFILE###
#DOCKERFILE###RUN gem install asciidoctor asciidoctor-pdf asciidoctor-diagram
#DOCKERFILE###RUN gem install coderay pygments.rb
#DOCKERFILE###
#DOCKERFILE###WORKDIR /documents
