
DIST_NAME = soaf.sh
DIST_VERSION = 1.0.0-dev

EXE_TGT = src/$(DIST_NAME)

EXE_SRC_CORE_LIST = \
  src/debug.sh \
  src/varargs.sh \
  src/util.sh \
  src/root.sh \
  src/version.sh \
  src/arg.sh \
  src/info.sh \
  src/var.sh \
  src/var_usage_exp.sh \
  src/usage.sh \
  src/console.sh \
  src/theme.sh \
  src/display.sh \
  src/roll.sh \
  src/log.sh \
  src/notif.sh \
  src/action.sh \
  src/appli.sh \
  src/engine.sh

EXE_SRC_EXTRA_LIST = \
  src/job.sh \
  src/state.sh \
  src/prop_file.sh \
  src/net_cfg.sh \
  src/notif_mail.sh \
  src/notif_sms_free.sh

EXE_SRC_MAIN_LIST = \
  src/main_tpl.sh \
  src/main_tpl_makefile \
  Makefile \
  src/main_tpl_makefile_eof \
  src/main.sh

SRC_LIST = \
  src/util_map.sh \
  src/util_list.sh \
  src/module.sh \
  src/which.sh \
  $(EXE_SRC_CORE_LIST) \
  $(EXE_SRC_EXTRA_LIST) \
  $(EXE_SRC_MAIN_LIST)

SRC_GENERATED_LIST = \
  src/define_.sh

EXTRA_DIST = \
  $(CHANGELOG_ADOC_FILE) \
  TODO \
  test/test.sh \
  test/cfg.sh \
  test/init.sh \
  test/module.sh

EXTRA_CLEAN = \
  test/log \
  test/notif \
  test/run \
  test/tmp.* \
  test/test.prop

EXTRA_ADOC_INCLUDE = \
  doc/attributes \
  doc/link-site
