
SRC_DIR = src
VER_FILE = $(SRC_DIR)/version.sh

DIST_NAME = \
  $(shell grep "_NAME=" $(VER_FILE) | awk -F\" '{print $$2}')
DIST_VERSION = \
  $(shell grep "_VERSION=" $(VER_FILE) | awk -F\" '{print $$2}')

LIB_TGT = $(SRC_DIR)/$(DIST_NAME)

LIB_SRC_LIST = \
  src/version.sh \
  src/cfg.sh \
  src/util.sh \
  src/user.sh \
  src/display.sh \
  src/roll.sh \
  src/log.sh \
  src/engine.sh \
  src/action.sh \
  src/init.sh

EXTRA_DIST = Makefile Makefile.cfg test.sh

EXTRA_CLEAN = $(DIST_NAME).log
