Guide of "Shell rOot Api Framework"
===================================
Denis Chancogne <denis.chancogne@free.fr>
v1.0.0, 25/07/2020
:toc: left
:sectnums:

== Quick startup

== Developers

=== Implementation syntax

Attribut name::
  [LIB]\_[FEATURE]\_[NAME]\_ATTR="[lib]\_[feature]_[name]"

.Example
********************************
SOAF_JOB_CMD_ATTR="soaf_job_cmd"
********************************

Property name::
  [LIB]\_[FEATURE]_[NAME]_PROP="[lib].[feature].[name]"

.Example
**********************************
SOAF_UTIL_DAY_PROP="soaf.util.day"
**********************************

Nature name::
  ([prefix].)[lib].[feature].[name]

.Example
***********************
$NATURE.soaf.state.prop
***********************

File name::
  [appli].([lib].[feature].)[name]

.Example :
***************************************
$APPLI_NAME.prop

$APPLI_NAME.soaf.state.inactive.$NATURE
***************************************

Action name::
  TODO

== Architecture

=== Natures

The script creates lot of natures. A nature is composed of attributes values
and functions. It has a unique name and created through a *create* function.

All features of a nature are in fact set through environment variables, with
unique name of nature and unique attribute name.

=== Engine

The engine processes several stages, in same order. The names of these stages
are : module, cfg, init, prepenv, execution.

==== Module stage (module)

TODO

==== Configuration stage (cfg)

This part allow to define value of variables. Variables are affected if they
are still empty with the function *soaf_cfg_set()*.

Engine start to source *cfg.sh* files into global then local directories.
Unless *SOAF_EXT_ALL_DIR* has been defined inside the application.
Then modules are configured in reverse order, starting with extern modules,
ending with application and soaf modules.

==== Initialisation stage (init)

This part allow to execute functions to initialize action environment : natures
creation, add info variables, add usage variables, ... Target is software
environment.

Engine start to source *init.sh* files, same way as *cfg.sh* files.
Then modules are initialized in reverse order, starting with extern modules,
ending with application and soaf modules.

==== Prepare environment stage (prepenv)

This part allow to prepare working environment : directory creation, ... Target
is system environment.

Engine start to initialize modules, starting soaf and application modules,
ending with extern modules.
Then it source *prepenv.sh* files, same way as *init.sh* files.

=== Modules

TODO

=== Application

TODO
