Guide of "Shell rOot Api Framework"
===================================
Denis Chancogne <denis.chancogne@free.fr>

== Quick startup

== Implementation normes

- attribut name
  [LIB]_[FEATURE]_[NAME]_ATTR="[lib]_[feature]_[name]"
  example :
    SOAF_JOB_CMD_ATTR="soaf_job_cmd"

- property name
  [LIB]_[FEATURE]_[NAME]_PROP="[lib].[feature].[name]"
  example :
    SOAF_UTIL_DAY_PROP="soaf.util.day"

- nature name
  ([prefix].)[lib].[feature].[name]
  example :
    $NATURE.soaf.state.prop

- file name
  [appli].([lib].[feature].)[name]
  example :
    $APPLI_NAME.prop
    $APPLI_NAME.soaf.state.$NATURE.inactive

- action name
  TODO

== Engine

=== Startup parts

==== Module part (module)

==== Configuration part (cfg)

This part allow to define value of variables. Variables are affected if they
are still empty with the function *soaf_cfg_set()*.

Engine start to source *cfg.sh* files into global then local directories.
Unless *SOAF_EXT_ALL_DIR* has been defined inside the application.
Then modules are configured in reverse order, starting with extern modules,
ending with application and soaf modules.

=== Initialisation part (init)

This part allow to execute functions to initialize action environment : natures
creation, add info variables, add usage variables, ... Target is software
environment.

Engine start to source *init.sh* files, same way as *cfg.sh* files.
Then modules are initialized in reverse order, starting with extern modules,
ending with application and soaf modules.

=== Prepare environment part (prepenv)

This part allow to prepare working environment : directory creation, ... Target
is system environment.

Engine start to initialize modules, starting soaf and application modules,
ending with extern modules.
Then it source *prepenv.sh* files, same way as *init.sh* files.

== Modules

== Application
